### ISSUE TITLE
source released

### ISSUE THREAD

**Issue by gtoal** [AaronBottegal/Defender-Source-Code#1]
In case you weren't aware of it:  https://github.com/historicalsource/defender
- very recent release.

**Comment by AaronBottegal** [comment]
I guess that's the end of this project, heh.

I'm going to continue cleaning it up, and eventually splitting it up and organizing it better for some porting work I'll probably show later. But for now I guess I'll just look at the real thing to see if I missed anything, heh.

Thanks for sharing, really cool and oddly timed though,. haha.
